### PR TITLE
add support for SRV records

### PR DESCRIPTION
**Pull request by nefilim**
thanks for dns4s, pretty slick implementation! i needed support for SRV record lookups and added some support, only tested my specific use case:

    IO(Dns) ? Dns.DnsPacket(Query ~ Questions(TypeSRV("_etcd._tcp.mino.internal")), new InetSocketAddress("10.0.0.2", 53)) onComplete {

and it seems to work ok with changes. 

ps. initially when i first cloned and attempted to build i had problems with this dependency not being found:

libraryDependencies ++= Seq(
      "io.netty" % "netty-handler" % "4.0.+"))

i changed it to 4.0.26.Final and it worked, when i forked & cloned the project i was able to build it without having to modify that dep requirement, i assume since my ivy cache was populated.

### CODE REVIEW

**Comment by mkroli** [comment]
Thank you very much for your pull request!

I never had an issue with the netty dependency on my own so I hope you're right with the problem being the ivy cache.

Could I please ask you to put the [ASLv2](http://apache.org/licenses/LICENSE-2.0#apply) license header to ```core/src/main/scala/com/github/mkroli/dns4s/section/resource/SRVResource.scala``` and do an additional commit?
A test case for the new resource record would be great as well however I would do this on my own but this will probably take some more time.

**Comment by nefilim** [comment]
I've added the ASLv2 header, I'm not sure what appropriate values are, please modify as needed. 

I've started a Spec for SRVResources but needs it a bit more work, if you could take a look please. 

Thanks!

**Comment by mkroli** [comment]
Thanks! The headers look good to me.
The Spec you've written looks good to me so far. I can add the one you commented out.

**Comment by mkroli** [comment]
I just released your SRVResource in v0.7. Thanks!

**Pull request merged**
