### PR TITLE
introduce edns client subnet option (WIP)

### PR DESCRIPTION
**Pull request by whatvn**
- the current EDNS option was not using, it's useless
- implement EDNS to include client ip option which is useful, described
  in this ietf draft by Google
https://tools.ietf.org/html/draft-vandergaast-edns-client-ip-01

@mkroli please take a look, thank

### CODE REVIEW

**Comment by mkroli** [comment]
Thanks for your work.

Currently I see the following issues:
- unnecessary formatting changes in not involved code
- your implementation restricts OPTResource to Client IP information while it should be able to include more options in the future
- also it should be possible to not include any option in OPTResource as the OPTResource without data defines the size of the DNS packet in the class section which in itself is useful

I think implementing "The variable part of an OPT RR" as defined in [rfc2671 section-4.4](https://tools.ietf.org/html/rfc2671#section-4.4) in a more general manner should be done before implementing a concrete instance of it.

What do you think?

**Comment by whatvn** [comment]
> unnecessary formatting changes in not involved code

yes, I did not notice this
> your implementation restricts OPTResource to Client IP information while it should be able to include more options in the future
Agree
> also it should be possible to not include any option in OPTResource as the OPTResource without data defines the size of the DNS packet in the class section which in itself is useful
> I think implementing "The variable part of an OPT RR" as defined in rfc2671 section-4.4 in a more general manner should be done before implementing a concrete instance of it.

As I know the edns client ip subnet has not been assigned option code yet. I agree it's better to implement a concrete instance of this option, but I am not sure where to go yet.

**Comment by whatvn** [comment]
One more thing is the `typeOPT` of EDNS Client subnet option is `41`, which is the same as `OPTResource`, I still don't figure out how to make concrete instance without modifying `OPTResource`

**Comment by mkroli** [comment]
Have a look at [rfc7871](https://tools.ietf.org/html/rfc7871).
I've created a prototype in 33c8a0d in branch [feature-rfc7871](https://github.com/mkroli/dns4s/tree/feature-rfc7871).
Tests and DSL implementation are yet to be developed.

You can use it like this:
```scala
IO(Dns) ? Dns.DnsPacket(Query ~ Questions(QName("google.de")) ~ Additional(append = false, RRClass(4096) ~ (OPTRecord(OPTResource.OPTOption(OPTResource.optionClientSubnet, OPTResource.ClientSubnetOPTOptionData(OPTResource.ClientSubnetOPTOptionData.familyIPv4, 24, 0, InetAddress.getByName("1.2.3.0"))) :: Nil))), new InetSocketAddress("8.8.8.8", 53))
```

What do you think?

**Comment by whatvn** [comment]
please see my comment on your commit. 
My use case is not on client side, I want my DNS server to process EDNS client subnet option, extract client IP (because OpenDNS and Google DNS include this option when querying my dns server) to identify its location, and optimize DNS responses based on user's location 
 
And one more thing, I found current coding style is a bit difficult for me to follow, doing thing likes: 

```
case class AClass(x: Int, y:Int) {
    def apply(...)
}

object AClass(...) {
   def apply(....) = new AClass(x, y )
}
```

look weird to me, I am new to scala, and I dont know if it's good practice or not.

**Comment by mkroli** [comment]
You can try the feature-rfc7871 branch and match messages like this:
```scala
case Query(_) ~ Additional(OPTRecord(OPTResource(OPTOption(8, ClientSubnetOPTOptionData(family, sourcePrefixLength, scopePrefixLength, address)) :: Nil)) :: Nil) =>
```

**Comment by mkroli** [comment]
feature-rfc7871 branch is merged on master

**Pull request closed without merging**
